# ============================================================
# Apache HTTPD 反向代理镜像 — Java 反序列化靶场
# ============================================================
FROM httpd:2.4

# 拷贝自定义配置
COPY apache/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY apache/my_vhost.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY apache/index.html /usr/local/apache2/htdocs/index.html

EXPOSE 80

CMD ["httpd-foreground"]
